### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by TheStngularity** [TheStngularity/SyrDB#2]
**File:** all code files
**Problem:** old license

**File:** src/types/dictionary.cpp, src/types/dictionary.h
**Problem:** Can use templates instead of a bunch of functions

**File:** specification/ru_RU/protocol.md
**Problem:** Grammatical errors

**Comment by EgorBron** [comment]
draft PR and branch? no?

**Comment by EgorBron** [comment]
and also you may should add some issue templates
